import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Soap from "@/components/Soap";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [soapList, setSoapList] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const data = await fetch("/api");
      const json = await data.json();

      setSoapList(json);
    };
    fetchData().catch(console.error);
  }, []);
  console.log("SOAPPPPPPPPPP", soapList);

  return (
    <>
      <Head>
        <title>Saponi-per-tutti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {soapList.map((soap) => {
          return <Soap key={soap._id} name={soap.name} price={soap.price} />;
        })}
      </main>
    </>
  );
}
