import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/effect-fade";
import { useRouter } from "next/router";
import HomeSoapCard from "@/components/HomeSoapCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [soapList, setSoapList] = useState([]);
  const [moreInfos, setMoreInfos] = useState(false);
  const [rating, setRating] = useState();
  const router = useRouter();

  useEffect(() => {
    const fetchData = async () => {
      const data = await fetch("/api/soaps/");
      const json = await data.json();

      setSoapList(json);
    };
    fetchData().catch(console.error);
  }, []);
  useEffect(() => {
    const fetchData = async () => {
      const data = await fetch("/api/comment");
      const json = await data.json();
      setRating(json);
    };
    fetchData().catch(console.error);
  }, []);

  return (
    <>
      <Head>
        <title>Saponi-per-tutti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSoapCard
        soapList={soapList}
        moreInfosFunction={setMoreInfos}
        moreInfosData={moreInfos}
      />
    </>
  );
}
